<h2>Košík</h2>
<p>
	<?= $this->error?>
</p>
<table id="Kosik">
	<tr>
		<th>Název</th>
		<th>Počet kusů</th>
		<th>Cena</th>
	</tr>
<?php
$celkovaCena = 0;
for($i = 0; $i<count($this->data['produkty']);$i++){
	echo <<<EOT
	<tr>
		<td><a href="index.php?strana=Produkt&id={$this->data['produkty'][$i]['id']}}">{$this->data['produkty'][$i]['nazev']}</a></td>
		<td>{$this->data['produkty'][$i]['pocet']}</td>
		<td>{$this->data['produkty'][$i]['cena']} Kč</td>
	</tr>
EOT;
$celkovaCena += $this->data['produkty'][$i]['cena']*$this->data['produkty'][$i]['pocet'];
}
?>
	<tr>
		<th>Celkem</th>
		<th></th>
		<th><?= $celkovaCena?> Kč</th>
	</tr>
</table>


