<h2>Přihlášení</h2>
<p>
	<?= $this->error ?>
</p>

<?php
#Vypisuje formulář jeno těm, kdo mají něco v košíku
	function prihlaseniFormular() {
	?>
		<form action="prihlaseni.php" method="post">

	    <table>
	    <tr><td><label for="uzivatelJmeno">Uživatelské jméno:</label></td>
			<td><input type="text" name="uzivatelJmeno" id="uzivatelJmeno"></td></tr>


			<tr><td><label for="uzivatelHeslo">Heslo:</label></td>
			<td><input type="password" name="uzivatelHeslo" id="uzivatelHeslo"></td></tr>


			<tr><td><input type="submit" value="Přihlásit" name="prihlasit"></td>  </tr>
		  </table>
	  </form>

<?php
}
?>

